services:
  php-apache:
    image: php
    container_name: php
    ports:
      - "8080:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "camagru"
    volumes:
      - dbData:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: camagru
      MYSQl_ROOT_PASSWORD: "password"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  app:
  dbData:

networks:
  mynetwork: